### ISSUE TITLE
Dependency "LNPreviewToContextMenu" has no shared framework schemes

### ISSUE THREAD

**Issue by trispo** [LeoNatan/LNPreviewToContextMenu#1]
Hi,

I get the error "Dependency "LNPreviewToContextMenu" has no shared framework schemes" when running Carthage update.

**Comment by LeoNatan** [comment]
Hello,

That's odd; the scheme is shared:

![Screen Shot 2019-09-25 at 17 05 31](https://user-images.githubusercontent.com/2270433/65608307-b0841980-dfb6-11e9-9a37-f9cb0ccc1cf4.png)

**Comment by LeoNatan** [comment]
I think it was a git ignore issue.

**Comment by LeoNatan** [comment]
Should work now. Happy coding!

**Comment by trispo** [comment]
Thanks, it works now.
